name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]
jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Auto Minify
        uses: nizarmah/auto-minify@v1.6
        with:
          # Directory that contains the files you want to minify. Defaults to current directory (.)
          directory: /css/* # optional, default is .
          # Directory that contains the minified files. Defaults to same directory
          output: /dist # optional, default is 
